name: Production workflow

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Development Codes
        uses: actions/checkout@v3
      - name: Use Node.js 17.x
        uses: actions/setup-node@v3
        with:
          node-version: 17.x
      - name: Install Dependencies
        run: yarn install
#       - name: Build
#         run: yarn run test
      - name: Build
        run: yarn run build --if-present
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          args: deploy --dir=build --prod
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'secondhand-teamseven'
          heroku_email: 'didapatria3@gmail.com'
